# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-08 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='scaned',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
        migrations.AlterField(
            model_name='orderbeton',
            name='scaned',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
        migrations.AlterField(
            model_name='personalorder',
            name='scaned',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
        migrations.AlterField(
            model_name='productswholesale',
            name='scaned',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
        migrations.AlterField(
            model_name='rentacar',
            name='scaned',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
    ]
