# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-08 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0002_auto_20190508_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_contacts', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_contacts', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('questions_contacts', models.TextField(max_length=500, verbose_name='Вопрос')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('scaned', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
        ),
    ]
