# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-08 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0005_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='product',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
