# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-08 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0007_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=150, verbose_name='Номер телефона')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('scaned', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
        ),
    ]
