# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-10 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import ecoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0011_auto_20190510_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=ecoapp.models.avatar_upload_to),
        ),
    ]
